In [1]:
import numpy as np 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
arr = np.arange(0,9)
arr = arr.reshape(3,3) 
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1)

array([0.75653647])

In [10]:
np.random.randn(25)

array([ 1.64668113, -0.14912409, -0.30912088, -0.48429346,  1.52249817,
        0.28570261,  0.23445617, -0.97173877, -0.90449811, -0.04076901,
       -0.57139391,  2.4979277 ,  0.3229143 , -0.05120449,  0.75110219,
        0.54329739, -0.27160309,  1.74366251, -0.89870114,  0.90475592,
       -0.13392661,  0.7189335 , -1.70059821, -0.06183139, -2.11950867])

In [11]:
arr = np.arange(0,1,0.01)
arr.reshape(10,10)

array([[0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09],
       [0.1 , 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19],
       [0.2 , 0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29],
       [0.3 , 0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39],
       [0.4 , 0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79],
       [0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89],
       [0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99]])

In [12]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [13]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [14]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [15]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
mat = np.arange(1,26).reshape(5,5)
mat[2,2]

13

In [17]:
mat[3,4]

20

In [18]:
mat[2,2:5]

array([13, 14, 15])

In [19]:
mat[2:5,2]

array([13, 18, 23])

In [20]:
mat[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [21]:
mat[0:3,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [22]:
mat[1:4,1:4]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [23]:
mat[3,4]

20

In [24]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [25]:
np.std(mat)

7.211102550927978

In [26]:
np.sum?

In [27]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

In [28]:
np.sum(mat,axis=1)

array([ 15,  40,  65,  90, 115])

In [29]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [30]:
m1 = np.arange(0,12)
m1.reshape(3,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [31]:
m1.dtype

dtype('int32')

In [32]:
m1.ndim

1

In [33]:
m1.shape

(12,)

In [34]:
marks=np.random.randint(0,100,20)

In [35]:
marks

array([74, 81, 83, 82, 42, 82, 42, 64, 99, 38, 36,  5, 57, 45, 73,  2, 32,
       10, 41, 12])

In [36]:
aes=np.sort(marks)
aes

array([ 2,  5, 10, 12, 32, 36, 38, 41, 42, 42, 45, 57, 64, 73, 74, 81, 82,
       82, 83, 99])

In [37]:
np.flip(aes)

array([99, 83, 82, 82, 81, 74, 73, 64, 57, 45, 42, 42, 41, 38, 36, 32, 12,
       10,  5,  2])

In [38]:
aes[:-1]

array([ 2,  5, 10, 12, 32, 36, 38, 41, 42, 42, 45, 57, 64, 73, 74, 81, 82,
       82, 83])

In [39]:
aes[::-1]

array([99, 83, 82, 82, 81, 74, 73, 64, 57, 45, 42, 42, 41, 38, 36, 32, 12,
       10,  5,  2])

In [40]:
aes[0:5]=90

In [41]:
aes

array([90, 90, 90, 90, 90, 36, 38, 41, 42, 42, 45, 57, 64, 73, 74, 81, 82,
       82, 83, 99])

In [42]:
sliceo=aes[0:5]
sliceo[:]=100
aes

array([100, 100, 100, 100, 100,  36,  38,  41,  42,  42,  45,  57,  64,
        73,  74,  81,  82,  82,  83,  99])

In [43]:
deep_copy_aes=np.copy(aes)
deep_copy_aes[:]

array([100, 100, 100, 100, 100,  36,  38,  41,  42,  42,  45,  57,  64,
        73,  74,  81,  82,  82,  83,  99])

In [44]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
np.eye(5).reshape(25)

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [46]:
np.eye(5).flatten()

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [47]:
v=np.arange(0,9).reshape(3,3)
v

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [48]:
n=np.arange(9,12)
n

array([ 9, 10, 11])

In [49]:
np.vstack((v,n)) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
s=np.append(v,[n],axis=0)

In [51]:
np.hsplit(s,3)

[array([[0],
        [3],
        [6],
        [9]]),
 array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]])]

In [52]:
 np.vsplit(s,4)

[array([[0, 1, 2]]),
 array([[3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11]])]

In [53]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [54]:
farr=np.random.uniform(1,20,5) 
farr

array([18.95058165, 15.43776819,  6.57416768, 11.54403104, 15.88082742])

In [55]:
np.ceil(farr)

array([19., 16.,  7., 12., 16.])

In [56]:
np.floor(farr)

array([18., 15.,  6., 11., 15.])

In [57]:
np.round(farr)

array([19., 15.,  7., 12., 16.])

In [30]:
j=np.random.randint(1,100,25).reshape(5,5)
j

array([[90, 46, 17,  4, 46],
       [41, 65, 43, 17, 58],
       [77, 14, 77, 35, 14],
       [ 3, 23, 24, 57, 97],
       [36, 70, 68, 26, 61]])

In [31]:
np.max(j,axis=0)

array([90, 70, 77, 57, 97])

In [32]:
np.min(j,axis=0)

array([ 3, 14, 17,  4, 14])

In [33]:
np.var(j,axis=0)

array([962.64, 492.24, 555.76, 318.16, 714.16])

In [61]:
np.std(j,axis=0)

array([17.69067551, 19.45661841, 25.68267899, 27.49108947, 23.23445717])

In [62]:
s=np.zeros(10)/0

C:\Users\singh\AppData\Local\Temp\ipykernel_9772\1639128199.py:1: RuntimeWarning: invalid value encountered in divide
  s=np.zeros(10)/0


In [63]:
s[6]=200
s

array([ nan,  nan,  nan,  nan,  nan,  nan, 200.,  nan,  nan,  nan])

In [64]:
s=np.arange(100,151)
s

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [65]:
np.flip(s)

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

In [66]:
np.arange(0,25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
s=np.arrray=[1,0,2,0,0,4,0,8]
s

[1, 0, 2, 0, 0, 4, 0, 8]

In [8]:
s=np.ones(100).reshape(10,10)
s

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
s[1:9,1:9]=0
s

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
a=np.ones((8,8))
a[0:2,::2]=0
a[1::2,1::2]=0
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [23]:
m1 = np.random.randint(1, 10, (3, 3))
m2 = np.random.randint(1, 10, (3, 3))
add= np.add(m1, m2)
mul = np.matmul(m1, m2)
sub = np.subtract(m1, m2)
m1
m2

array([[6, 3, 1],
       [3, 7, 7],
       [6, 4, 6]])

In [27]:
import numpy as np
m1 = np.random.randint(1, 10, (3, 3))
m2 = np.random.randint(1, 10, (3, 3))
add = np.add(m1, m2)
mul = np.matmul(m1, m2)
sub = np.subtract(m1, m2)
print(m1)

print(m2)

print(add)

print(mul)

print(sub)


[[5 9 8]
 [6 1 7]
 [9 3 6]]
[[6 3 2]
 [1 3 7]
 [9 1 6]]
[[11 12 10]
 [ 7  4 14]
 [18  4 12]]
[[111  50 121]
 [100  28  61]
 [111  42  75]]
[[-1  6  6]
 [ 5 -2  0]
 [ 0  2  0]]


In [9]:
a = np.ones((8, 8))
a[1::2, ::2] = 0 
a[::2, 1::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])